name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
  
    - cron: '30 6 * * *'
    - cron: '0 13 * * *'
    - cron: '0 18 * * *'
    - cron: '21 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install deps
      run: pip install feedparser requests beautifulsoup4 ebooklib

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python rss.py
